#!/bin/bash
#PBS -N redcom_-PSS0.25ADebug
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o refffdcommunCIFAR_Channel_Undirected_SWk8_A-k8-AdjSW-nr200-S-K20-EE1-SM_segType_cucuDebugger-PSS-PSnmbhFinallM2L.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 CIFAR_DFL_reducedSharingCuDebugger.py Chhannel88le_Undirected_oofu_ A -k 4 -Adj AK -nr 2 -S -K 10 -EE 1 -SM cu -PSS 0.77

#END OF SCRIPT
