#!/bin/bash
#PBS -N red0401_-PSS0.1B1
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_debug0401lessB1-k4-AdjSW-nr4-S-K10-SM_segType_ll-PSS-PSS0.1.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedDebug0401.py debug0401less B1 -k 4 -Adj SW -nr 4 -S -K 10 -SM l  -PSS 0.1

#END OF SCRIPT