#!/bin/bash
#PBS -N redcom_-PSS0.25A
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunCIFAR_layerFirstTry_URS_A-k4-nr250-S-URS-K20-EE1-PSS-PSS0.25.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 CIFAR_DFL_reducedSharing.py layerFirstTry_URS_ A -k 4 -nr 250 -S -URS -K 20 -EE 1  -PSS 0.25

#END OF SCRIPT