#!/bin/bash
#PBS -N redcom_-PSS0.8B1u
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_srn_FirstTest_MNIST_c_B1u-k4-AdjAK-nr200-S-K20-SM_segType_cucu-SRN-PSS-PSS0.8.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedSharing.py srn_FirstTest_MNIST_c_ B1u -k 4 -Adj AK -nr 200 -S -K 20 -SM cu -SRN  -PSS 0.8

#END OF SCRIPT