#!/bin/bash
#PBS -N redcom_-PSS0.9B1
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_srnFirstTest_B1-k4-AdjAK-nr50-S-K20-SM_segType_cc-SRN-PSS-PSS0.9.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedSharing.py srnFirstTest_ B1 -k 4 -Adj AK -nr 50 -S -K 20 -SM c -SRN  -PSS 0.9

#END OF SCRIPT