#!/bin/bash
#PBS -N redcom_-PSS0.25B1
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_tryMNIST_no_CRS_EE05_cuSW_B1-k4-AdjSW-nr100-S-K20-SM_segType_cucu-EE0.5-PSS-PSS0.25.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedSharing.py tryMNIST_no_CRS_EE05_cuSW_ B1 -k 4 -Adj SW -nr 100 -S -K 20 -SM cu -EE 0.5  -PSS 0.25

#END OF SCRIPT