#!/bin/bash
#PBS -N redcom_-PSS0.8B1
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_tryMNIST_no_CRS_record_layer0_EE025_cSW_B1-k4-AdjSW-nr200-S-K20-SM_segType_cc-EE0.25-PSS-PSS0.8.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedSharing.py tryMNIST_no_CRS_record_layer0_EE025_cSW_ B1 -k 4 -Adj SW -nr 200 -S -K 20 -SM c -EE 0.25  -PSS 0.8

#END OF SCRIPT