#!/bin/bash
#PBS -N redcom_-PSS0.1B1
#PBS -A GT-cabdallah3
#PBS -l nodes=1:ppn=16
#PBS -l pmem=2gb
#PBS -l walltime=07:45:00
#PBS -j oe
#PBS -o redcommunMNIST_tryMNIST_fSW_URS_B1-k4-AdjSW-nr120-S-K20-SM_segType_ff-URS-PSS-PSS0.1.out
#PBS -m abe
#PBS -M zzhang433@gatech.edu

cd $PBS_O_WORKDIR
module load pytorch
python3 MNIST_DFL_reducedSharing.py tryMNIST_fSW_URS_ B1 -k 4 -Adj SW -nr 120 -S -K 20 -SM f -URS  -PSS 0.1

#END OF SCRIPT